name: pretium
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  animated_text_kit: ^4.2.3 # A collection of ready-to-use animated text widgets
  cupertino_icons: ^1.0.8 # Cupertino-style icons (iOS) for Flutter apps
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1 # A predictable state management library using the BLoC pattern
  freezed_annotation: ^3.0.0 # Annotations for code generation with freezed (immutable classes and unions)
  get_it: ^8.0.3 # A simple service locator for dependency injection
  injectable: ^2.5.0 # Dependency injection generator to use with get_it
  shared_preferences: ^2.5.3 # Plugin to persist simple data (e.g., settings) locally
  styled_widget: ^0.4.1 # Provides syntactic sugar for styling widgets
  textstyle_extensions: ^2.0.0-nullsafety # Extensions on `TextStyle` for easier manipulation

dev_dependencies:
  build_runner: ^2.4.15 # Code generator utility to run generators like freezed, json_serializable
  flutter_lints: ^5.0.0 # Recommended linter rules for Flutter apps
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6 # Code generator for data classes, unions/pattern-matching (used with freezed_annotation)
  injectable_generator: ^2.7.0 # Generates code for injectable (DI) setup
  json_serializable: ^6.9.5 # Generates code for JSON serialization/deserialization

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: TrebuchetMS
      fonts:
        - asset: assets/fonts/Trebuchet-MS.ttf

